name: trivy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 15 * * 1'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images with docker-compose
        run: |
          docker-compose build
          # Récupérer l'ID de l'image pour le frontend
          FRONTEND_IMAGE_ID=$(docker-compose images -q react-nginx)
          # Tagger l'image pour Trivy
          docker tag $FRONTEND_IMAGE_ID docker.io/my-organization/frontend:${{ github.sha }}
          # Récupérer l'ID de l'image pour le backend
          BACKEND_IMAGE_ID=$(docker-compose images -q springboot-docker-container)
          # Tagger l'image pour Trivy
          docker tag $BACKEND_IMAGE_ID docker.io/my-organization/backend:${{ github.sha }}

      - name: Run Trivy vulnerability scanner (Frontend)
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/frontend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-frontend.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner (Backend)
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/backend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-backend.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab (Frontend)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-frontend.sarif'

      - name: Upload Trivy scan results to GitHub Security tab (Backend)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-backend.sarif'