name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Scan Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend image
        run: docker build -t docker.io/my-organization/my-back:${{ github.sha }} ./back_employee

      - name: Build frontend image
        run: docker build -t docker.io/my-organization/my-front:${{ github.sha }} ./front_employee

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/my-organization/my-back:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/my-organization/my-front:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'